const technicianDetails = {
    "Benitez, Felix": {
        photo: "images/Benitez.png",
        role: "Service Technician",
        classification: "BT Permit",
        location: "Glenview, IL",
        startDate: "2025-05-30",
        unionDate: null,
        birthDate: "1998-07-27",
        vehicleNumber: "Veh-91",
        licensePlate: "4058089B",
	    ladderRack: false,
        specialty: "Refrigeration Specialist",
        certifications: ["EPA Universal", "A2L Refrigerant"],
        training: [],
	    supervisor: "Patrick Rocco"
    },

    "Chudzinski, Jason": {
        photo: "images/Chudzinski.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Lemont, IL",
        startDate: "2022-10-24",
        unionDate: "2024-04-22",
        birthDate: "1988-02-21",
        vehicleNumber: "Veh-58",
        licensePlate: "530111D",
	    ladderRack: false,
        specialty: "Roof tops and packaged units",
        certifications: ["EPA Universal", "A2L Refrigerant"],
        training: [           
             { name: "RBI Boiler Training", status: "Completed", date: "2025-08-13" }],
	    supervisor: "Dan Perez"
    },

    "Hulsman, Nicholas": {
        photo: "images/Hulsman.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Carol Stream, IL",
        startDate: "2023-10-23",
        unionDate: "2012-04-01",
        birthDate: "1986-04-16",
        vehicleNumber: "Veh-75",
        licensePlate: "520228D",
	    ladderRack: false,
        specialty: "Rooftop Unit Specialist",
        certifications: ["EPA Universal", "OSHA 10", "Brazing"],
        training: [            
	    { name: "Carrier i-Vu", status: "Completed", date: null },
        { name: "Tridium Niagara", status: "Completed", date: null},
        { name: "ABB VFD", status: "Completed", date: null },
        { name: "Honeywell VFD", status: "Completed", date: null }],
	    supervisor: "Jason Weeks"
    },

    "Izzo, Gil": {
        photo: "images/Izzo.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Evergreen Park, IL",
        startDate: "2017-05-15",
        unionDate: null,
        birthDate: "1971-05-29",
        vehicleNumber: "Veh-71",
        licensePlate: "521827D",
	    ladderRack: false,
        specialty: "BAS/Controls Specialist , Low-Voltage", 
        certifications: ["EPA Universal", "A2L REfrigerant", "OSHA 10"], 
        training: [
            { name: "Carrier Controls Expert Level Training", status: "Completed", date: null },
            { name: "Carrier OPEN BACnet Controls Series Level II", status: "Completed", date: "2025-05-08" },
            { name: "Toshiba VRF Startup", status: "Completed", date: "2024-02-07" }],
	    supervisor: "Jason Weeks"
    },

    "Kwiatkowski, Mitch": {
        photo: "images/Kwiatkowski.jpg",
        role: "Apprentice",
        classification: "Apprentice, Yr 4",
        location: "Arlington Heights, IL",
        startDate: "2022-03-28",
        unionDate: "2022-04-01",
        birthDate: "1998-04-27",
        vehicleNumber: "Veh-57",
        licensePlate: "530112D",
	    ladderRack: false,
        specialty: "Rooftop Unit Specialist",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [
            { name: "Trane-Mitsubishi CITY MULTI VRF Training", status: "Completed", date: "2024-12-06" },
            { name: "Daikin VRV Install Class", status: "Completed", date: "2024-03-20" }],	
	    supervisor: "Patrick Rocco"
    },

    "Lewis, Jeremy": {
        photo: "images/Lewis.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Homer Glen, IL",
        startDate: "2019-04-08",
        unionDate: "2019-04-01",
        birthDate: "1977-04-16",
        vehicleNumber: "Veh-56",
        licensePlate: "527496D",
	    ladderRack: false,
        specialty: "Rooftop Unit Specialist",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [            
            { name: "RBI Boiler Training", status: "Completed", date: "2025-08-13" }],
	    supervisor: "Dan Perez"

    },

    "Lopez, Leobani": {
        photo: "images/Lopez.png",
        role: "Apprentice",
        classification: "Apprentice, Yr 1",
        location: "Aurora, IL",
        startDate: "2025-03-17",
        unionDate: "2025-04-01",
        birthDate: "2000-11-27",
        vehicleNumber: "Veh-93",
        licensePlate: "228300C",
	    ladderRack: false,
        specialty: "N/A",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [],
	    supervisor: "Patrick Rocco"
    },

    "McAuliffe, Jacob": {
        photo: "images/McAuliffe.jpg",
        role: "Apprentice",
        classification: "Apprentice, Yr 2",
        location: "Tinley Park, IL",
        startDate: "2024-03-25",
        unionDate: "2024-04-01",
        birthDate: "1993-04-08",
        vehicleNumber: "Veh-96",
        licensePlate: "229405C",
	    ladderRack: false,
        specialty: "N/A",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [],
	    supervisor: "Dan Perez"
    },

    "Nichols, Chris": {
        photo: "images/Nichols.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Joliet, IL",
        startDate: "2019-01-11",
        unionDate: "2019-02-11",
        birthDate: "1981-08-21",
        vehicleNumber: "Veh-50",
        licensePlate: "203501C",
	    ladderRack: false,
        specialty: "N/A",
        certifications: ["EPA Universal", "OSHA 10", "A2L Refrigerant"],
        training: [
            { name: "Samsung Install Training", status: "Completed", date: "2023-07-27" },
            { name: "Trane-Mitsubishi CITY MULTI VRF Training", status: "Completed", date: "2024-12-06" },
],
	    supervisor: "Patrick Rocco"
    },

    "Perez, Dan": {
        photo: "images/Perez.jpg",
        role: "Field Service Supervisor/Team Lead",
        classification: "BT Journeyman",
        location: "Schererville, IN",
        startDate: "2014-04-28",
        unionDate: null,
        birthDate: "1972-07-25",
        vehicleNumber: "Veh-67",
        licensePlate: "513484D",
	    ladderRack: true,
        specialty: "Boiler / Hydronics Specialist",
        certifications: ["EPA Universal", "OSHA 10", "A2L Refrigerant"],
        training: [
            { name: "RBI Boiler Training", status: "Completed", date: "2025-08-13" }],
	    supervisor: "Jennine Israel (SOM)"
    },

    "Rieck, Chris": {
        photo: "images/Rieck.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Hoffman Estates, IL",
        startDate: "2023-10-30",
        unionDate: "2007-06-01",
        birthDate: "1998-07-12",
        vehicleNumber: "Veh-73",
        licensePlate: "520227D",
	    ladderRack: false,
        specialty: "Piping / Rigging Specialist",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant", "BA Construction Management"],
        training: [
            { name: "RBI Boiler Training", status: "Completed", date: "2025-08-13" },
            { name: "Toshiba VRF Startup", status: "Completed", date: "2024-02-07" }],

	    supervisor: "Jason Weeks"
    },

    "Rizzuti, Jeremy": {
        photo: "images/Rizzuti.jpg",
        role: "Apprentice",
        classification: "Apprentice, Yr 3",
        location: "Joliet, IL",
        startDate: "2023-03-27",
        unionDate: "2023-04-01",
        birthDate: "1997-04-30",
        vehicleNumber: "Veh-94",
        licensePlate: "229403C",
	    ladderRack: false,
        specialty: "Rooftop Unit Specialist",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [           
             { name: "Daikin VRV Install Class", status: "Completed", date: "2024-03-20" },
             { name: "Trane-Mitsubishi CITY MULTI VRF Training", status: "Completed", date: "2024-12-06" }],
	    supervisor: "Patrick Rocco"
    },

    "Rocco, Patrick": {
        photo: "images/Rocco.jpg",
        role: "Field Service Supervisor/Team Lead",
        classification: "BT Journeyman",
        location: "Beecher, IL",
        startDate: "2018-04-16",
        unionDate: "2018-04-01",
        birthDate: "1993-08-14",
        vehicleNumber: "Veh-70",
        licensePlate: "514777D",
	    ladderRack: true,
        specialty: "VRF Specialist",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [
            { name: "Daikin VRV Install Class", status: "Completed", date: "2024-03-20" },	
            { name: "Mitsubishi VRF Masterclass", status: "Completed", date: "2023-05-20"},
            { name: "Toshiba VRF Startup", status: "Completed", date: "2024-02-07" },

        ],
	    supervisor: "Jennine Israel (SOM)"
    },

    "Rodriguez, Rafael": {
        photo: "images/Rodriguez.jpg",
        role: "Apprentice",
        classification: "Apprentice, Yr 1",
        location: "Romeoville, IL",
        startDate: "2025-09-22",
        unionDate: "2025-10-01",
        birthDate: "1999-12-01",
        vehicleNumber: "Veh-92",
        licensePlate: "IL-FB142",
	    ladderRack: false,
        specialty: "N/A",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [],
	supervisor: "Dan Perez"
    },

    "Schulz, Cory": {
        photo: "images/Schulz.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Niles, IL",
        startDate: "2024-09-30",
        unionDate: "2025-04-15",
        birthDate: "1993-11-16",
        vehicleNumber: "Veh-84",
        licensePlate: "213227C",
	    ladderRack: true,
        specialty: "Packaged Unit Install Specialist",
        certifications: ["EPA Universal", "OSHA 30", "A2L Refrigerant"],
        training: [           
             { name: "Trane-Mitsubishi CITY MULTI VRF Training", status: "Completed", date: "2024-12-06" },
],
	supervisor: "Jason Weeks"
    },

    "Stan, Victor": {
        photo: "images/Stan.jpg",
        role: "Service Technician",
        classification: "BT Journeyman",
        location: "Chicago, IL (Jefferson Park)",
        startDate: "2024-09-23",
        unionDate: "2025-04-15",
        birthDate: "1984-08-25",
        vehicleNumber: "Veh-83",
        licensePlate: "533867D",
	    ladderRack: false,
        specialty: "Refrigeration Specialist",
        certifications: ["EPA Universal", "A2L Refrigerant", "OSHA 10"],
        training: [],
	supervisor: "Patrick Rocco"
    },

    "Weeks, Jason": {
        photo: "images/Weeks.jpg",
        role: "Quality Assurance Supervisor",
        classification: "BT Journeyman",
        location: "Manhattan, IL",
        startDate: "2019-10-28",
        unionDate: null,
        birthDate: "1998-04-07",
        vehicleNumber: "Veh-68",
        licensePlate: "513485D",
	    ladderRack: true,
        specialty: "Air-side HVAC Specialist",
        certifications: ["EPA Universal", "OSHA 10", "A2L Refrigerant"],
        training: [
            { name: "LU 597 Boiler/Burner 1 & 2", status: "Completed", date: null },
            { name: "Hydronics 1 & 2", status: "Completed", date: null },
            { name: "Centrifugal Chillers 1 & 2", status: "Completed", date: null},
            { name: "DDC Controls 1 & 2", status: "Completed", date: null },
            { name: "Trane-Mitsubishi CITY MULTI VRF Training", status: "Completed", date: null },
            { name: "LG VRF", status: "Completed", date: null },
            { name: "Samsung VRF", status: "Completed", date: null},
            { name: "Daikin VRV Install Class", status: "Completed", date: "2024-03-20" },
            { name: "Toshiba VRF Startup", status: "Completed", date: "2024-02-07" }],
	    supervisor: "Jennine Israel (SOM)",
}
}

const skillMasterList = [
    { "name": "Packaged Rooftop Units (RTUs)", "category": "Packaged / Unitary Equipment" },
    { "name": "Split Systems (AC/HP, <25 Tons)", "category": "Packaged / Unitary Equipment" },
    { "name": "Furnaces (Gas/Oil/Electric)", "category": "Packaged / Unitary Equipment" },
    { "name": "Air Handling Units (AHUs)", "category": "Packaged / Unitary Equipment" },
    { "name": "V/PTAC's & Other Self-Contained Units", "category": "Packaged / Unitary Equipment" },
    { "name": "Variable Refrigerant Flow (VRF) systems", "category": "VRF Systems" },
    { "name": "Commercial Refrigeration", "category": "Commercial Refrigeration Equipment" },
    { "name": "Water Source Heat Pumps", "category": "Hydronic Systems" },
    { "name": "Pumps (Hydronic)", "category": "Hydronic Systems" },
    { "name": "Cooling Towers", "category": "Hydronic Systems" },
    { "name": "Boilers (Hydronic & Steam)", "category": "Hydronic Systems" },
    { "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "category": "Controls" },
    { "name": "Motor Starters / VFDs", "category": "Controls" },
    { "name": "VAV Boxes", "category": "Controls" },
    { "name": "Terminals", "category": "Controls" },
    { "name": "Electrical Diagnostics / Troubleshooting", "category": "Additional Skills / Foundational" },
    { "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "category": "Additional Skills / Foundational" },
    { "name": "Evacuation, Purging and leak search procedure", "category": "Additional Skills / Foundational" },
    { "name": "Brazing / Pipefitting", "category": "Additional Skills / Foundational" },
    { "name": "Safety Procedures & Certifications", "category": "Additional Skills / Foundational" },
    { "name": "Heat Transfer Knowledge", "category": "Building Envelope" },
    { "name": "Air Infiltration Awareness", "category": "Building Envelope" },
    { "name": "System Sizing and Efficiency Impact", "category": "Building Envelope" },
    { "name": "Moisture and Vapor Barrier Understanding", "category": "Building Envelope" },
    { "name": "Application in Field Work", "category": "Building Envelope" },
    { "name": "Safety Adherence & Advocacy", "category": "Safety & Professionalism" },
    { "name": "Attitude & Commitment", "category": "Safety & Professionalism" },
    { "name": "Reliability & Punctuality", "category": "Safety & Professionalism" },
    { "name": "Professional Appearance", "category": "Safety & Professionalism" },
    { "name": "Worksite Cleanliness", "category": "Safety & Professionalism" },
    { "name": "Internal Communication", "category": "Communication & Documentation" },
    { "name": "Effective Customer Interaction", "category": "Communication & Documentation" },
    { "name": "Service Report Accuracy", "category": "Communication & Documentation" },
    { "name": "Customer Documentation Quality & Timeliness", "category": "Communication & Documentation" },
    { "name": "Check-in/Out & Update Procedures", "category": "Job Performance & Efficiency" },
    { "name": "Productivity & Time Management", "category": "Job Performance & Efficiency" },
    { "name": "Effective Job Resolution", "category": "Job Performance & Efficiency" },
    { "name": "Workmanship Quality", "category": "Job Performance & Efficiency" },
    { "name": "Follow-Up Task Management", "category": "Job Performance & Efficiency" },
    { "name": "Lead Generation (Pull-Through)", "category": "Business Development & Process" },
    { "name": "Supports Overtime Needs", "category": "Business Development & Process" },
];

const skillsData = [
    // Benitez, Felix
    { "technician": "Benitez, Felix", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Split Systems (AC/HP, <25 Tons)", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Furnaces (Gas/Oil/Electric)", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Air Handling Units (AHUs)", "level": 3 },
    { "technician": "Benitez, Felix", "name": "V/PTAC's & Other Self-Contained Units", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Variable Refrigerant Flow (VRF) systems", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Commercial Refrigeration", "level": 5 },
    { "technician": "Benitez, Felix", "name": "Water Source Heat Pumps", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Pumps (Hydronic)", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Cooling Towers", "level": 2 },
    { "technician": "Benitez, Felix", "name": "Boilers (Hydronic & Steam)", "level": 2 },
    { "technician": "Benitez, Felix", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 2 },
    { "technician": "Benitez, Felix", "name": "Motor Starters / VFDs", "level": 2 },
    { "technician": "Benitez, Felix", "name": "VAV Boxes", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Terminals", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Electrical Diagnostics / Troubleshooting", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Benitez, Felix", "name": "Evacuation, Purging and leak search procedure", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Brazing / Pipefitting", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Heat Transfer Knowledge", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Benitez, Felix", "name": "System Sizing and Efficiency Impact", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Moisture and Vapor Barrier Understanding", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Application in Field Work", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Attitude & Commitment", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Reliability & Punctuality", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Professional Appearance", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Internal Communication", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Effective Customer Interaction", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Customer Documentation Quality & Timeliness", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Benitez, Felix", "name": "Productivity & Time Management", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Effective Job Resolution", "level": 5 },
    { "technician": "Benitez, Felix", "name": "Workmanship Quality", "level": 3 },
    { "technician": "Benitez, Felix", "name": "Follow-Up Task Management", "level": 5 },
    { "technician": "Benitez, Felix", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Benitez, Felix", "name": "Supports Overtime Needs", "level": 5 },
    
    // Chudzinski, Jason
    { "technician": "Chudzinski, Jason", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Variable Refrigerant Flow (VRF) systems", "level": 2 },
    { "technician": "Chudzinski, Jason", "name": "Commercial Refrigeration", "level": 3 },
    { "technician": "Chudzinski, Jason", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Pumps (Hydronic)", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Cooling Towers", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Boilers (Hydronic & Steam)", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 3 },
    { "technician": "Chudzinski, Jason", "name": "Motor Starters / VFDs", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "VAV Boxes", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Terminals", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Electrical Diagnostics / Troubleshooting", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Heat Transfer Knowledge", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Chudzinski, Jason", "name": "System Sizing and Efficiency Impact", "level": 3 },
    { "technician": "Chudzinski, Jason", "name": "Moisture and Vapor Barrier Understanding", "level": 3 },
    { "technician": "Chudzinski, Jason", "name": "Application in Field Work", "level": 3 },
    { "technician": "Chudzinski, Jason", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Attitude & Commitment", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Professional Appearance", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Internal Communication", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Effective Customer Interaction", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Customer Documentation Quality & Timeliness", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Productivity & Time Management", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Effective Job Resolution", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Workmanship Quality", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Chudzinski, Jason", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Chudzinski, Jason", "name": "Supports Overtime Needs", "level": 5 },
    
    // Hulsman, Nicholas
    { "technician": "Hulsman, Nicholas", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Variable Refrigerant Flow (VRF) systems", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "Commercial Refrigeration", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Pumps (Hydronic)", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Cooling Towers", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Boilers (Hydronic & Steam)", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Motor Starters / VFDs", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "VAV Boxes", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Terminals", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Electrical Diagnostics / Troubleshooting", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Evacuation, Purging and leak search procedure", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Heat Transfer Knowledge", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "System Sizing and Efficiency Impact", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "Moisture and Vapor Barrier Understanding", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Application in Field Work", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "Reliability & Punctuality", "level": 1 },
    { "technician": "Hulsman, Nicholas", "name": "Professional Appearance", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Internal Communication", "level": 4 },
    { "technician": "Hulsman, Nicholas", "name": "Effective Customer Interaction", "level": 2 },
    { "technician": "Hulsman, Nicholas", "name": "Service Report Accuracy", "level": 2 },
    { "technician": "Hulsman, Nicholas", "name": "Customer Documentation Quality & Timeliness", "level": 2 },
    { "technician": "Hulsman, Nicholas", "name": "Check-in/Out & Update Procedures", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "Productivity & Time Management", "level": 2 },
    { "technician": "Hulsman, Nicholas", "name": "Effective Job Resolution", "level": 2 },
    { "technician": "Hulsman, Nicholas", "name": "Workmanship Quality", "level": 3 },
    { "technician": "Hulsman, Nicholas", "name": "Follow-Up Task Management", "level": 2 },
    { "technician": "Hulsman, Nicholas", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Hulsman, Nicholas", "name": "Supports Overtime Needs", "level": 5 },
    
    // Izzo, Gil
    { "technician": "Izzo, Gil", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Izzo, Gil", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Variable Refrigerant Flow (VRF) systems", "level": 3 },
    { "technician": "Izzo, Gil", "name": "Commercial Refrigeration", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Pumps (Hydronic)", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Cooling Towers", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Boilers (Hydronic & Steam)", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Motor Starters / VFDs", "level": 5 },
    { "technician": "Izzo, Gil", "name": "VAV Boxes", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Terminals", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Electrical Diagnostics / Troubleshooting", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Safety Procedures & Certifications", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Heat Transfer Knowledge", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Air Infiltration Awareness", "level": 5 },
    { "technician": "Izzo, Gil", "name": "System Sizing and Efficiency Impact", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Moisture and Vapor Barrier Understanding", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Application in Field Work", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Safety Adherence & Advocacy", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Izzo, Gil", "name": "Reliability & Punctuality", "level": 3 },
    { "technician": "Izzo, Gil", "name": "Professional Appearance", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Worksite Cleanliness", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Internal Communication", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Service Report Accuracy", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Customer Documentation Quality & Timeliness", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Check-in/Out & Update Procedures", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Productivity & Time Management", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Effective Job Resolution", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Workmanship Quality", "level": 5 },
    { "technician": "Izzo, Gil", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Lead Generation (Pull-Through)", "level": 4 },
    { "technician": "Izzo, Gil", "name": "Supports Overtime Needs", "level": 2 },

    //Kwiatkowski, Mitch
    { "technician": "Kwiatkowski, Mitch", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Split Systems (AC/HP, <25 Tons)", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Furnaces (Gas/Oil/Electric)", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Air Handling Units (AHUs)", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "V/PTAC's & Other Self-Contained Units", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Variable Refrigerant Flow (VRF) systems", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Commercial Refrigeration", "level": 1 },
    { "technician": "Kwiatkowski, Mitch", "name": "Water Source Heat Pumps", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Pumps (Hydronic)", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Cooling Towers", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Boilers (Hydronic & Steam)", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Motor Starters / VFDs", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "VAV Boxes", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Terminals", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Electrical Diagnostics / Troubleshooting", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Kwiatkowski, Mitch", "name": "Brazing / Pipefitting", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Heat Transfer Knowledge", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "System Sizing and Efficiency Impact", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Moisture and Vapor Barrier Understanding", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Application in Field Work", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Kwiatkowski, Mitch", "name": "Professional Appearance", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Internal Communication", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Effective Customer Interaction", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Customer Documentation Quality & Timeliness", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Kwiatkowski, Mitch", "name": "Productivity & Time Management", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Effective Job Resolution", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Workmanship Quality", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Follow-Up Task Management", "level": 3 },
    { "technician": "Kwiatkowski, Mitch", "name": "Lead Generation (Pull-Through)", "level": 2 },
    { "technician": "Kwiatkowski, Mitch", "name": "Supports Overtime Needs", "level": 4 },

    // Lewis, Jeremy
    { "technician": "Lewis, Jeremy", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Split Systems (AC/HP, <25 Tons)", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Furnaces (Gas/Oil/Electric)", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Air Handling Units (AHUs)", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "V/PTAC's & Other Self-Contained Units", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Variable Refrigerant Flow (VRF) systems", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Commercial Refrigeration", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Water Source Heat Pumps", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Pumps (Hydronic)", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Cooling Towers", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Boilers (Hydronic & Steam)", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Motor Starters / VFDs", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "VAV Boxes", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Terminals", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Electrical Diagnostics / Troubleshooting", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Evacuation, Purging and leak search procedure", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Brazing / Pipefitting", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Heat Transfer Knowledge", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Air Infiltration Awareness", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "System Sizing and Efficiency Impact", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Moisture and Vapor Barrier Understanding", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Application in Field Work", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Safety Adherence & Advocacy", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Reliability & Punctuality", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Professional Appearance", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Lewis, Jeremy", "name": "Internal Communication", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Effective Customer Interaction", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Service Report Accuracy", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Customer Documentation Quality & Timeliness", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Check-in/Out & Update Procedures", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Productivity & Time Management", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Effective Job Resolution", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Workmanship Quality", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Follow-Up Task Management", "level": 3 },
    { "technician": "Lewis, Jeremy", "name": "Lead Generation (Pull-Through)", "level": 2 },
    { "technician": "Lewis, Jeremy", "name": "Supports Overtime Needs", "level": 3 },
    
    // Lopez, Leobani
    { "technician": "Lopez, Leobani", "name": "Packaged Rooftop Units (RTUs)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Split Systems (AC/HP, <25 Tons)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Furnaces (Gas/Oil/Electric)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Air Handling Units (AHUs)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "V/PTAC's & Other Self-Contained Units", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Variable Refrigerant Flow (VRF) systems", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Commercial Refrigeration", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Water Source Heat Pumps", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Pumps (Hydronic)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Cooling Towers", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Boilers (Hydronic & Steam)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Motor Starters / VFDs", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "VAV Boxes", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Terminals", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Electrical Diagnostics / Troubleshooting", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Evacuation, Purging and leak search procedure", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Brazing / Pipefitting", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Safety Procedures & Certifications", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Heat Transfer Knowledge", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Air Infiltration Awareness", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "System Sizing and Efficiency Impact", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Moisture and Vapor Barrier Understanding", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Application in Field Work", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Safety Adherence & Advocacy", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Attitude & Commitment", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Reliability & Punctuality", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Professional Appearance", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Worksite Cleanliness", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Internal Communication", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Effective Customer Interaction", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Service Report Accuracy", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Customer Documentation Quality & Timeliness", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Check-in/Out & Update Procedures", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Productivity & Time Management", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Effective Job Resolution", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Workmanship Quality", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Follow-Up Task Management", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Lead Generation (Pull-Through)", "level": 1 },
    { "technician": "Lopez, Leobani", "name": "Supports Overtime Needs", "level": 1 },
    
    // McAuliffe, Jacob
    { "technician": "McAuliffe, Jacob", "name": "Packaged Rooftop Units (RTUs)", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Split Systems (AC/HP, <25 Tons)", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Furnaces (Gas/Oil/Electric)", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Air Handling Units (AHUs)", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "V/PTAC's & Other Self-Contained Units", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Variable Refrigerant Flow (VRF) systems", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Commercial Refrigeration", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Water Source Heat Pumps", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Pumps (Hydronic)", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Cooling Towers", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Boilers (Hydronic & Steam)", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Motor Starters / VFDs", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "VAV Boxes", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Terminals", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Electrical Diagnostics / Troubleshooting", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Evacuation, Purging and leak search procedure", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Brazing / Pipefitting", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Safety Procedures & Certifications", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Heat Transfer Knowledge", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Air Infiltration Awareness", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "System Sizing and Efficiency Impact", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Moisture and Vapor Barrier Understanding", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Application in Field Work", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Attitude & Commitment", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Reliability & Punctuality", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Professional Appearance", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Internal Communication", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Effective Customer Interaction", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Customer Documentation Quality & Timeliness", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "McAuliffe, Jacob", "name": "Productivity & Time Management", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Effective Job Resolution", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Workmanship Quality", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Follow-Up Task Management", "level": 3 },
    { "technician": "McAuliffe, Jacob", "name": "Lead Generation (Pull-Through)", "level": 2 },
    { "technician": "McAuliffe, Jacob", "name": "Supports Overtime Needs", "level": 2 },

    // Nichols, Chris
    { "technician": "Nichols, Chris", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Nichols, Chris", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Nichols, Chris", "name": "Air Handling Units (AHUs)", "level": 4 },
    { "technician": "Nichols, Chris", "name": "V/PTAC's & Other Self-Contained Units", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Variable Refrigerant Flow (VRF) systems", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Commercial Refrigeration", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Nichols, Chris", "name": "Pumps (Hydronic)", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Cooling Towers", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Boilers (Hydronic & Steam)", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Motor Starters / VFDs", "level": 4 },
    { "technician": "Nichols, Chris", "name": "VAV Boxes", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Terminals", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Electrical Diagnostics / Troubleshooting", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Nichols, Chris", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Safety Procedures & Certifications", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Heat Transfer Knowledge", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Nichols, Chris", "name": "System Sizing and Efficiency Impact", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Moisture and Vapor Barrier Understanding", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Application in Field Work", "level": 2 },
    { "technician": "Nichols, Chris", "name": "Safety Adherence & Advocacy", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Reliability & Punctuality", "level": 2 },
    { "technician": "Nichols, Chris", "name": "Professional Appearance", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Worksite Cleanliness", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Internal Communication", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Nichols, Chris", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Customer Documentation Quality & Timeliness", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Productivity & Time Management", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Effective Job Resolution", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Workmanship Quality", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Nichols, Chris", "name": "Lead Generation (Pull-Through)", "level": 3 },
    { "technician": "Nichols, Chris", "name": "Supports Overtime Needs", "level": 4 },
    
    // Perez, Dan
    { "technician": "Perez, Dan", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Perez, Dan", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Perez, Dan", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Perez, Dan", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Perez, Dan", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Perez, Dan", "name": "Variable Refrigerant Flow (VRF) systems", "level": 5 },
    { "technician": "Perez, Dan", "name": "Commercial Refrigeration", "level": 5 },
    { "technician": "Perez, Dan", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Perez, Dan", "name": "Pumps (Hydronic)", "level": 5 },
    { "technician": "Perez, Dan", "name": "Cooling Towers", "level": 5 },
    { "technician": "Perez, Dan", "name": "Boilers (Hydronic & Steam)", "level": 5 },
    { "technician": "Perez, Dan", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 5 },
    { "technician": "Perez, Dan", "name": "Motor Starters / VFDs", "level": 5 },
    { "technician": "Perez, Dan", "name": "VAV Boxes", "level": 5 },
    { "technician": "Perez, Dan", "name": "Terminals", "level": 5 },
    { "technician": "Perez, Dan", "name": "Electrical Diagnostics / Troubleshooting", "level": 5 },
    { "technician": "Perez, Dan", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Perez, Dan", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Perez, Dan", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Perez, Dan", "name": "Safety Procedures & Certifications", "level": 5 },
    { "technician": "Perez, Dan", "name": "Heat Transfer Knowledge", "level": 5 },
    { "technician": "Perez, Dan", "name": "Air Infiltration Awareness", "level": 5 },
    { "technician": "Perez, Dan", "name": "System Sizing and Efficiency Impact", "level": 5 },
    { "technician": "Perez, Dan", "name": "Moisture and Vapor Barrier Understanding", "level": 5 },
    { "technician": "Perez, Dan", "name": "Application in Field Work", "level": 5 },
    { "technician": "Perez, Dan", "name": "Safety Adherence & Advocacy", "level": 5 },
    { "technician": "Perez, Dan", "name": "Attitude & Commitment", "level": 5 },
    { "technician": "Perez, Dan", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Perez, Dan", "name": "Professional Appearance", "level": 5 },
    { "technician": "Perez, Dan", "name": "Worksite Cleanliness", "level": 5 },
    { "technician": "Perez, Dan", "name": "Internal Communication", "level": 5 },
    { "technician": "Perez, Dan", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Perez, Dan", "name": "Service Report Accuracy", "level": 5 },
    { "technician": "Perez, Dan", "name": "Customer Documentation Quality & Timeliness", "level": 5 },
    { "technician": "Perez, Dan", "name": "Check-in/Out & Update Procedures", "level": 5 },
    { "technician": "Perez, Dan", "name": "Productivity & Time Management", "level": 5 },
    { "technician": "Perez, Dan", "name": "Effective Job Resolution", "level": 5 },
    { "technician": "Perez, Dan", "name": "Workmanship Quality", "level": 5 },
    { "technician": "Perez, Dan", "name": "Follow-Up Task Management", "level": 5 },
    { "technician": "Perez, Dan", "name": "Lead Generation (Pull-Through)", "level": 4 },
    { "technician": "Perez, Dan", "name": "Supports Overtime Needs", "level": 5 },
    
    // Rieck, Chris
    { "technician": "Rieck, Chris", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Rieck, Chris", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Variable Refrigerant Flow (VRF) systems", "level": 1 },
    { "technician": "Rieck, Chris", "name": "Commercial Refrigeration", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Water Source Heat Pumps", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Pumps (Hydronic)", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Cooling Towers", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Boilers (Hydronic & Steam)", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 3 },
    { "technician": "Rieck, Chris", "name": "Motor Starters / VFDs", "level": 4 },
    { "technician": "Rieck, Chris", "name": "VAV Boxes", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Terminals", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Electrical Diagnostics / Troubleshooting", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Brazing / Pipefitting", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Safety Procedures & Certifications", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Heat Transfer Knowledge", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Air Infiltration Awareness", "level": 4 },
    { "technician": "Rieck, Chris", "name": "System Sizing and Efficiency Impact", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Moisture and Vapor Barrier Understanding", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Application in Field Work", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Safety Adherence & Advocacy", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Rieck, Chris", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Professional Appearance", "level": 5 },
    { "technician": "Rieck, Chris", "name": "Worksite Cleanliness", "level": 2 },
    { "technician": "Rieck, Chris", "name": "Internal Communication", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Effective Customer Interaction", "level": 2 },
    { "technician": "Rieck, Chris", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Customer Documentation Quality & Timeliness", "level": 3 },
    { "technician": "Rieck, Chris", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Productivity & Time Management", "level": 3 },
    { "technician": "Rieck, Chris", "name": "Effective Job Resolution", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Workmanship Quality", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Lead Generation (Pull-Through)", "level": 4 },
    { "technician": "Rieck, Chris", "name": "Supports Overtime Needs", "level": 5 },
    
    // Rizzuti, Jeremy
    { "technician": "Rizzuti, Jeremy", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Split Systems (AC/HP, <25 Tons)", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Furnaces (Gas/Oil/Electric)", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Air Handling Units (AHUs)", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "V/PTAC's & Other Self-Contained Units", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Variable Refrigerant Flow (VRF) systems", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Commercial Refrigeration", "level": 2 },
    { "technician": "Rizzuti, Jeremy", "name": "Water Source Heat Pumps", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Pumps (Hydronic)", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Cooling Towers", "level": 2 },
    { "technician": "Rizzuti, Jeremy", "name": "Boilers (Hydronic & Steam)", "level": 2 },
    { "technician": "Rizzuti, Jeremy", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 2 },
    { "technician": "Rizzuti, Jeremy", "name": "Motor Starters / VFDs", "level": 2 },
    { "technician": "Rizzuti, Jeremy", "name": "VAV Boxes", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Terminals", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Electrical Diagnostics / Troubleshooting", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Rizzuti, Jeremy", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Heat Transfer Knowledge", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "System Sizing and Efficiency Impact", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Moisture and Vapor Barrier Understanding", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Application in Field Work", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Attitude & Commitment", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Reliability & Punctuality", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Professional Appearance", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Internal Communication", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Effective Customer Interaction", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Customer Documentation Quality & Timeliness", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Productivity & Time Management", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Effective Job Resolution", "level": 2 },
    { "technician": "Rizzuti, Jeremy", "name": "Workmanship Quality", "level": 3 },
    { "technician": "Rizzuti, Jeremy", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Rizzuti, Jeremy", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Rizzuti, Jeremy", "name": "Supports Overtime Needs", "level": 2 },
    
    // Rocco, Patrick
    { "technician": "Rocco, Patrick", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Variable Refrigerant Flow (VRF) systems", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Commercial Refrigeration", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Pumps (Hydronic)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Cooling Towers", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Boilers (Hydronic & Steam)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Motor Starters / VFDs", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "VAV Boxes", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Terminals", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Electrical Diagnostics / Troubleshooting", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Brazing / Pipefitting", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Safety Procedures & Certifications", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Heat Transfer Knowledge", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Air Infiltration Awareness", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "System Sizing and Efficiency Impact", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Moisture and Vapor Barrier Understanding", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Application in Field Work", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Safety Adherence & Advocacy", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Attitude & Commitment", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Professional Appearance", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Worksite Cleanliness", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Internal Communication", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Service Report Accuracy", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Customer Documentation Quality & Timeliness", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Check-in/Out & Update Procedures", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Productivity & Time Management", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Effective Job Resolution", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Workmanship Quality", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Follow-Up Task Management", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Rocco, Patrick", "name": "Supports Overtime Needs", "level": 5 },

    // Rodriguez, Rafael 
    { "technician": "Rodriguez, Rafael", "name": "Packaged Rooftop Units (RTUs)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Split Systems (AC/HP, <25 Tons)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Furnaces (Gas/Oil/Electric)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Air Handling Units (AHUs)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "V/PTAC's & Other Self-Contained Units", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Variable Refrigerant Flow (VRF) systems", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Commercial Refrigeration", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Water Source Heat Pumps", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Pumps (Hydronic)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Cooling Towers", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Boilers (Hydronic & Steam)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Motor Starters / VFDs", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "VAV Boxes", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Terminals", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Electrical Diagnostics / Troubleshooting", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Evacuation, Purging and leak search procedure", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Brazing / Pipefitting", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Safety Procedures & Certifications", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Heat Transfer Knowledge", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Air Infiltration Awareness", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "System Sizing and Efficiency Impact", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Moisture and Vapor Barrier Understanding", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Application in Field Work", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Safety Adherence & Advocacy", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Attitude & Commitment", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Reliability & Punctuality", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Professional Appearance", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Worksite Cleanliness", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Internal Communication", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Effective Customer Interaction", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Service Report Accuracy", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Customer Documentation Quality & Timeliness", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Check-in/Out & Update Procedures", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Productivity & Time Management", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Effective Job Resolution", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Workmanship Quality", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Follow-Up Task Management", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Lead Generation (Pull-Through)", "level": 1 },
    { "technician": "Rodriguez, Rafael", "name": "Supports Overtime Needs", "level": 1 },
    
    // Schulz, Cory
    { "technician": "Schulz, Cory", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Air Handling Units (AHUs)", "level": 4 },
    { "technician": "Schulz, Cory", "name": "V/PTAC's & Other Self-Contained Units", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Variable Refrigerant Flow (VRF) systems", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Commercial Refrigeration", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Pumps (Hydronic)", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Cooling Towers", "level": 2 },
    { "technician": "Schulz, Cory", "name": "Boilers (Hydronic & Steam)", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Motor Starters / VFDs", "level": 4 },
    { "technician": "Schulz, Cory", "name": "VAV Boxes", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Terminals", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Electrical Diagnostics / Troubleshooting", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Safety Procedures & Certifications", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Heat Transfer Knowledge", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Air Infiltration Awareness", "level": 3 },
    { "technician": "Schulz, Cory", "name": "System Sizing and Efficiency Impact", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Moisture and Vapor Barrier Understanding", "level": 3 },
    { "technician": "Schulz, Cory", "name": "Application in Field Work", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Attitude & Commitment", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Professional Appearance", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Internal Communication", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Service Report Accuracy", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Customer Documentation Quality & Timeliness", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Check-in/Out & Update Procedures", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Productivity & Time Management", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Effective Job Resolution", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Workmanship Quality", "level": 4 },
    { "technician": "Schulz, Cory", "name": "Follow-Up Task Management", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Schulz, Cory", "name": "Supports Overtime Needs", "level": 5 },
    
    // Stan, Victor
    { "technician": "Stan, Victor", "name": "Packaged Rooftop Units (RTUs)", "level": 4 },
    { "technician": "Stan, Victor", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Stan, Victor", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Stan, Victor", "name": "Air Handling Units (AHUs)", "level": 4 },
    { "technician": "Stan, Victor", "name": "V/PTAC's & Other Self-Contained Units", "level": 4 },
    { "technician": "Stan, Victor", "name": "Variable Refrigerant Flow (VRF) systems", "level": 2 },
    { "technician": "Stan, Victor", "name": "Commercial Refrigeration", "level": 5 },
    { "technician": "Stan, Victor", "name": "Water Source Heat Pumps", "level": 4 },
    { "technician": "Stan, Victor", "name": "Pumps (Hydronic)", "level": 4 },
    { "technician": "Stan, Victor", "name": "Cooling Towers", "level": 3 },
    { "technician": "Stan, Victor", "name": "Boilers (Hydronic & Steam)", "level": 3 },
    { "technician": "Stan, Victor", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 2 },
    { "technician": "Stan, Victor", "name": "Motor Starters / VFDs", "level": 4 },
    { "technician": "Stan, Victor", "name": "VAV Boxes", "level": 4 },
    { "technician": "Stan, Victor", "name": "Terminals", "level": 4 },
    { "technician": "Stan, Victor", "name": "Electrical Diagnostics / Troubleshooting", "level": 4 },
    { "technician": "Stan, Victor", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 4 },
    { "technician": "Stan, Victor", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Stan, Victor", "name": "Brazing / Pipefitting", "level": 4 },
    { "technician": "Stan, Victor", "name": "Safety Procedures & Certifications", "level": 4 },
    { "technician": "Stan, Victor", "name": "Heat Transfer Knowledge", "level": 3 },
    { "technician": "Stan, Victor", "name": "Air Infiltration Awareness", "level": 4 },
    { "technician": "Stan, Victor", "name": "System Sizing and Efficiency Impact", "level": 4 },
    { "technician": "Stan, Victor", "name": "Moisture and Vapor Barrier Understanding", "level": 3 },
    { "technician": "Stan, Victor", "name": "Application in Field Work", "level": 4 },
    { "technician": "Stan, Victor", "name": "Safety Adherence & Advocacy", "level": 4 },
    { "technician": "Stan, Victor", "name": "Attitude & Commitment", "level": 5 },
    { "technician": "Stan, Victor", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Stan, Victor", "name": "Professional Appearance", "level": 5 },
    { "technician": "Stan, Victor", "name": "Worksite Cleanliness", "level": 4 },
    { "technician": "Stan, Victor", "name": "Internal Communication", "level": 4 },
    { "technician": "Stan, Victor", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Stan, Victor", "name": "Service Report Accuracy", "level": 4 },
    { "technician": "Stan, Victor", "name": "Customer Documentation Quality & Timeliness", "level": 4 },
    { "technician": "Stan, Victor", "name": "Check-in/Out & Update Procedures", "level": 4 },
    { "technician": "Stan, Victor", "name": "Productivity & Time Management", "level": 4 },
    { "technician": "Stan, Victor", "name": "Effective Job Resolution", "level": 4 },
    { "technician": "Stan, Victor", "name": "Workmanship Quality", "level": 4 },
    { "technician": "Stan, Victor", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Stan, Victor", "name": "Lead Generation (Pull-Through)", "level": 5 },
    { "technician": "Stan, Victor", "name": "Supports Overtime Needs", "level": 5 },
    
    // Weeks, Jason
    { "technician": "Weeks, Jason", "name": "Packaged Rooftop Units (RTUs)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Split Systems (AC/HP, <25 Tons)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Furnaces (Gas/Oil/Electric)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Air Handling Units (AHUs)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "V/PTAC's & Other Self-Contained Units", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Variable Refrigerant Flow (VRF) systems", "level": 4 },
    { "technician": "Weeks, Jason", "name": "Commercial Refrigeration", "level": 4 },
    { "technician": "Weeks, Jason", "name": "Water Source Heat Pumps", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Pumps (Hydronic)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Cooling Towers", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Boilers (Hydronic & Steam)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Controls Systems (Pneumatic, DDC General, Specific Platforms)", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Motor Starters / VFDs", "level": 5 },
    { "technician": "Weeks, Jason", "name": "VAV Boxes", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Terminals", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Electrical Diagnostics / Troubleshooting", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Refrigeration Cycle Fundamentals & Troubleshooting", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Evacuation, Purging and leak search procedure", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Brazing / Pipefitting", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Safety Procedures & Certifications", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Heat Transfer Knowledge", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Air Infiltration Awareness", "level": 5 },
    { "technician": "Weeks, Jason", "name": "System Sizing and Efficiency Impact", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Moisture and Vapor Barrier Understanding", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Application in Field Work", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Safety Adherence & Advocacy", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Attitude & Commitment", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Reliability & Punctuality", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Professional Appearance", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Worksite Cleanliness", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Internal Communication", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Effective Customer Interaction", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Service Report Accuracy", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Customer Documentation Quality & Timeliness", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Check-in/Out & Update Procedures", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Productivity & Time Management", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Effective Job Resolution", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Workmanship Quality", "level": 5 },
    { "technician": "Weeks, Jason", "name": "Follow-Up Task Management", "level": 4 },
    { "technician": "Weeks, Jason", "name": "Lead Generation (Pull-Through)", "level": 4 },
    { "technician": "Weeks, Jason", "name": "Supports Overtime Needs", "level": 3 }]

const categoryDetails = {
    "Packaged / Unitary Equipment": {
        equipment: ["Packaged Rooftop Units (RTUs)","Make-Up Air Units (MAUs)","Dedicated Outdoor Air Systems (DOAS)","Computer Room Air Conditioners (CRAC)","Split Systems (Air Conditioners & Heat Pumps)","Gas & Electric Furnaces","Air Handling Units (AHUs)","Exhaust Fans (General, Kitchen, Lab)","Energy/Heat Recovery Ventilators (ERVs/HRVs)","Vertical/Package Terminal Air Conditioners (V/PTACs)","Self-Contained Units"],
        note: "A proficiency of Level 2 (Intermediate) or higher is recommended for most equipment in this category."
    },
    "VRF Systems": {
        equipment: ["Variable Refrigerant Flow (VRF) / Variable Refrigerant Volume (VRV) Outdoor Units","Indoor Fan Coil Units (Wall-mount, Ceiling Cassette, Ducted)","Branch Selector / Controller Boxes","Heat Recovery & Heat Pump Systems"],
        note: "A proficiency of Level 3 (Advanced) or higher is recommended for most of this equipment."
    },
    "Commercial Refrigeration Equipment": {
        equipment: ["Walk-In Coolers & Freezers","Reach-In Refrigerators & Freezers","Ice Machines","Refrigerated Prep Tables & Display Cases"],
        note: "A proficiency of Level 3 (Advanced) or higher is recommended for most of this equipment."
    },
    "Hydronic Systems": {
        equipment: ["Chillers (Air-Cooled, Water-Cooled, Scroll, Screw)","Boilers (Hydronic, Steam)","Cooling Towers","Pumps (Centrifugal, In-line, Base-mounted)","Water Source Heat Pumps","Heat Exchangers (Plate & Frame, Shell & Tube)"],
        note: "A proficiency of Level 3 (Advanced) or higher is recommended for most of this equipment."
    },
    "Controls": {
        equipment: ["Direct Digital Controls (DDC) Systems (General)","Building Automation System (BAS) Platforms (e.g., Carrier i-Vu, Johnson Controls Metasys, Trane Tracer)","Pneumatic Control Systems","Variable Air Volume (VAV) Boxes & Controls","Variable Frequency Drives (VFDs)","Motor Starters, Actuators, and Sensors"],
        note: "A proficiency of Level 3 (Advanced) or higher is recommended for most of this equipment."
    },
    "Additional Skills / Foundational": { equipment: [] }, "Building Envelope": { equipment: [] }, "Safety & Professionalism": { equipment: [] }, "Communication & Documentation": { equipment: [] }, "Job Performance & Efficiency": { equipment: [] }, "Business Development & Process": { equipment: [] }
};